# Generated by Django 3.2.2 on 2021-05-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sys', '0002_auto_20210530_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryform',
            name='des',
            field=models.TextField(),
        ),
    ]
