# Generated by Django 3.2.2 on 2021-05-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sys', '0003_alter_queryform_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNumber', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('addressField', models.TextField()),
                ('cityField', models.CharField(max_length=30)),
                ('stateField', models.CharField(max_length=30)),
                ('lastCropSown', models.CharField(max_length=30)),
                ('soilType', models.CharField(max_length=30)),
                ('cropType', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='queryform',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
