# Generated by Django 3.2.2 on 2021-05-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sys', '0004_auto_20210531_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorybooking',
            name='mobileNumber',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
