# Generated by Django 3.2.2 on 2021-05-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sys', '0007_laboratorybooking_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorybooking',
            name='dateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
